apiVersion: apps/v1
kind: Deployment
metadata:
  name: rev-hire-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rev-hire-app
  template:
    metadata:
      labels:
        app: rev-hire-app
    spec:
      containers:
      - name: rev-hire-container
        image: vinithmh/revature_backend_hiring_application:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rev-hire-service
spec:
  selector:
    app: rev-hire-app
  ports:
    - protocol: TCP
      port: 8888  # Expose externally on port 8888
      targetPort: 8000  # Route traffic internally to port 8000
  type: NodePort
